version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : 123
